### ISSUE TITLE
Open source license missing

### ISSUE THREAD

**Issue by filhocf** [akshayKMR/oorja#5]
Hi

I have interesting to translate this software to brazilian portuguese (pt-BR) and could not find any translation support, and when I got a look in the code, I saw that your license is a closed and copyrighted license (if you don't explicit the license and its terms, is licensed in copyright).

My suggestion is to use something like Apache or MIT licenses. Many people will feel more comfortable to contribute.

**Comment by akshayKMR** [comment]
Hi @filhocf,
I've decided for this project to be open source but it is not FOSS as you said.
I want it to be free for personal (non commercial) use, while also allowing users to make modifications to the code.

---

As for translations, it currently requires some work. The UI components currently have hardcoded english strings. l've planned to make them dynamic based on browser locale; and to load them from a json file such as  `pt-br.json`.
example: 
```json
{
    "thank.you": "obrigado"
}
```

When this is done, translations can be easily added for all languages.

**Comment by filhocf** [comment]
Thank you by your fast reply, @akshayKMR, but I see a mistake here. A software considered open source have a license recognized by Open Source Iniciative (https://opensource.org/). I understand your point, but in this way isn't a open source, is free (as beer) and you accept contributions. 

Haven't problems in use a specific license, but it need to explain what you can or can't to do, or in other words, need to explain for volunteers, like me, that your code is free and what I can do with it.

I work with open source, as volunteer, since 2000 and I did the translation for pt-BR and other minor contributions in other areas for OpenOffice, Mozilla (before of firefox), PosgreSQL, RoundCube, Jitsi, Debian and a lot of other softwares because I use in my work and some times for companies. 

I can use your software without you know, but this isn't my profile. This is a non ethic use, so I prefer don't help, but looking by other side, I see that you have a good idea in your hands and it can grow a lot. As I saw, I'm the brazilian translator for Jitsi, other webRTC and (really) open source project. I help there since before to be bought by Atlasian, a giant IT company. Today, Jitsi yet is a open sourced code and its developers work in a big company and with a good money in pocket. ;-)

Only some data for you to think about. and adjust your license (and explanations) for future supporters.

**Comment by akshayKMR** [comment]
Well in that case I couldn't find better words to describe the project whose source code is available (not a compiled binary or minified) for all to run and modify.
I'll give this some thought, but for now I want this project to be free for personal (non commercial) use.

Thanks.

**Comment by zicklag** [comment]
> I want this project to be free for personal (non commercial) use.

Does this mean I am not permitted to host this myself for my own business to use for communication or that I am simply not able to make money by selling or otherwise making money off of this software? If it is the latter, I'm pretty sure that the GPL license is around what you are looking for.

Either way I was planning on hosting this myself for my business to allow communication between members and potentially for hosting public meetings. Is that outside of what you are wanting to allow?

**Comment by zicklag** [comment]
Nevermind about the GPL, I blanked out there. I don't think that is what you want. Oops. :slightly_smiling_face:

**Comment by akshayKMR** [comment]
Initially this project was meant to completely open source. I thought it would be very cool given the extensibility of features using `tabs`.
Later, I felt a license such as APACHE or MIT can be utilized unfairly given my efforts. oorja is more of a small product rather than a resuable library. So I made it free for personal, non-commercial use.
A commercial business can contact me if they wish to use my project for a small fee. I believe such an arrangement will help me in invest more time in oorja, making it better; while also allowing individuals to experiment/extend it, like I had intended earlier.

Feel free to ask me any questions. I'm happy to answer them here or over email `akshay.kmr4321@gmail.com`

**Comment by zicklag** [comment]
OK, thanks. Right now me and my team don't have an actual business around what we do yet, but are planning on making one and are standing up all of our tooling with Open Source and free software. We can't afford to purchase any tooling right now especially when we can run everything on free tools. We will just have to use something else for the time being.

**Comment by zicklag** [comment]
@akshayKMR After talking with my partners we decided that we might be able to afford purchasing you product if it was a one-time fee for use of the product. How much would it cost to purchase the product?

**Comment by akshayKMR** [comment]
@zicklag you can e-mail me with your use case and requirements so that we can draft a suitable license. `akshay.kmr4321@gmail.com`

**Comment by zicklag** [comment]
@akshayKMR I ended up figure out how to get our Nextcloud Talk software running, so we ended up going with that. I still think that you did a really good job with this software, though. :smiley:
